name: Autosquash
description: Automatically update PRs with outdated checks and squash and merge the ones matching all branch protections.
runs:
  using: node12
  main: dist/index.js
branding:
  icon: box
  color: yellow
