version: 2.1

jobs:
  check:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn run build
      - run: yarn run eslint
      - run:
          name: Check action built
          command: |
            if output=$(git status --porcelain) && [ -z "$output" ]; then
              echo "Git status clean"
            else
              git status
              echo "Git status not clean. Did you forget to build the action before committing?"
              exit 1
            fi

workflows:
  check:
    jobs:
      - check:
          filters:
            branches:
              ignore:
                - master
